### ISSUE TITLE
Set the environment variable to make the JS engine emit JS coverage information

### ISSUE THREAD

**Issue by marco-c** [marco-c/coverage-crawler#1]

**Comment by Sush0512** [comment]
Hi @marco-c 
I would like to work on this issue. Could you please provide some description of the issue.

**Comment by marco-c** [comment]
The Firefox JavaScript engine emits coverage information in the directory specified in the JS_CODE_COVERAGE_OUTPUT_DIR environment variable.
We need to set this env variable to a temporary directory where the coverage information will be emitted, before running the crawler (so in crawler.py).
