### ISSUE TITLE
Make the crawler use the Firefox code coverage build downloaded by the latest_cov_build.py script

### ISSUE THREAD

**Issue by marco-c** [marco-c/coverage-crawler#12]

**Comment by rhcu** [comment]
There is a part of `crawler.py` that interacts with children links of the current one (input, button, links). After each interaction, as I understand, code coverage build is updated and new latest one is created. However, each artifact weights quite much (~700Mb) to download every time. Should we think about the content of coverage build download at that step or just to understand where the function should be called?

**Comment by marco-c** [comment]
No, the build (which is basically Firefox, just with coverage instrumentation) needs to be downloaded only once (and we can manually update it using the script).
The crawler just needs to use that build instead of the normal Firefox that is installed on the system.

**Comment by marco-c** [comment]
The crawler right now is using this:
https://github.com/marco-c/coverage-crawler/blob/master/crawler.py#L182
It should instead use the coverage build downloaded with the script.

**Comment by rhcu** [comment]
Thanks, it's clearer now. I can try to work on this issue. :)
