### ISSUE TITLE
When downloading latest coverage build, also download latest geckodriver version in the tools/ directory

### ISSUE THREAD

**Issue by marco-c** [marco-c/coverage-crawler#14]

**Comment by rhcu** [comment]
Hi @marco-c 

Here I can suggest creating Shell script that will identify OS of the user to download the appropriate release from here `https://api.github.com/repos/mozilla/geckodriver/releases/latest` using `grep` to find the name of OS.

Or, in Python it could be done in almost the same way: 
1) Get the latest version number from` https://api.github.com/repos/mozilla/geckodriver/releases/latest`;
2) Identify OS name of the user;
3) Create URL that will look smth like that: `https://github.com/mozilla/geckodriver/releases/download/VERSION_FROM_STEP_1/geckodriver-v0.20.0-linux64.tar.gz` for Linux or `https://github.com/mozilla/geckodriver/releases/download/VERSION_FROM_STEP_1/geckodriver-v0.20.0-macos.tar.gz` for MacOS;
4) urlretrieve it into `/tools` directory. Decompress. 

* According to `https://github.com/vladikoff/node-geckodriver` there could be some problems with installation on Windows. Should I consider them?

Is it the right approach to work on? 
Thanks.

**Comment by marco-c** [comment]
The Python option looks nicer to me, but a shell script works too. Choose what you prefer ;)

Regarding Windows problems, we can ignore them for now and figure them out later.
