### ISSUE TITLE
Add instructions on installation and usage to README

### ISSUE THREAD

**Issue by rhcu** [marco-c/coverage-crawler#15]
Can I add some more instructions on the project usage to README? 
Thanks.

**Comment by rhcu** [comment]
Something like that: 

# Usage on the local machine

- Create and activate Python 3.6 virtual environment
- In the virtual environment install requirements for the project running `pip install -r requirements`
- To install testing utilities run `pip install -r test-requirements.txt`
- If you want to test Python file with Flake8 run `flake8 name_or_file.py`
- Download and decompress the latest release of `Geckodriver` from [here](https://github.com/mozilla/geckodriver/releases) and move Geckodriver to the `/usr/local/bin` directory
- run `latest_cov_build.py` to download the latest coverage build of Firefox
- run `crawler.py`

**Comment by marco-c** [comment]
Yes, sure! Hopefully with #14 the geckodriver step won't be needed anymore.

**Comment by DGRamya** [comment]
Hello @marco-c,
I guess download decompress geckodriver should be updated in the README file, I was also stuck with the same error. Can I make the changes to README?

**Comment by marco-c** [comment]
@DGRamya once #21 is merged, the geckodriver step won't be needed anymore.
