### ISSUE TITLE
Set the environment variables to make gcov emit coverage information in a directory we choose

### ISSUE THREAD

**Issue by marco-c** [marco-c/coverage-crawler#19]
Similar to #1.

Here's an example of what we do for Firefox tests: https://dxr.mozilla.org/mozilla-central/source/testing/mozharness/mozharness/mozilla/testing/codecoverage.py#90.

**Comment by rhcu** [comment]
Hi! 
Can I add lines of code that configure `GCOV_PREFIX` and `GCOV_PREFIX_STRIP` in `latest_cov_build.py`, where I am already checking the version of OS as it is done with `mozinfo` library in `codecoverage.py` code?

**Comment by marco-c** [comment]
Those env variables are used by Firefox during the execution, so we should set them before executing Firefox using Selenium.
If we set them in latest_cov_build.py they won't have an effect when running the crawler.
