### ISSUE TITLE
When downloading latest coverage build, also download gcno archive and chrome-map.json file from the build machine

### ISSUE THREAD

**Issue by marco-c** [marco-c/coverage-crawler#20]
The gcno archive contains files that are necessary in order to parse coverage information (they contain the "structure" of the code).

The chrome-map.json is instead needed in order to generate JavaScript coverage reports: Firefox's URLs to source files (e.g.`resource://gre/modules/osfile/osfile_async_worker.js`) need to be translated to the actual path of the source file (e.g. `toolkit/components/osfile/modules/osfile_async_worker.js`). The chrome-map.json file contains a mapping between those URLs and the actual paths to the files.

**Comment by marco-c** [comment]
To see the artifacts generated by a Firefox build, you can go here:
https://treeherder.mozilla.org/#/jobs?repo=mozilla-central&filter-searchStr=linux ccov build
Then select one of the green "B".

In the "Job Details" tab at the bottom, you will see the generated artifacts. We will need `target.code-coverage-gcno.zip` and `chrome-map.json`.

**Comment by rhcu** [comment]
Just to clarify, we don't need to worry about the specific version or the latest release? And, we don't need to decompress downloaded archive?

**Comment by marco-c** [comment]
These files are specific for a given build (they are regenerated on every build, as they could change for every build since the Firefox source code changes), so we just need to make sure that they are downloaded together with the build.

In the future, we might want them decompressed, but for now it's fine to just download them.

**Comment by marco-c** [comment]
Fixed by #22.
