### ISSUE TITLE
Update .gitignore

### ISSUE THREAD

**Issue by rhcu** [marco-c/coverage-crawler#27]
There is `firefox` folder with the latest coverage build, gcno archive, and `chrome-map.json` files that, probably, do not need to be committed to the remote. Can I add them to .gitignore?

**Comment by marco-c** [comment]
Can you modify the script to download and extract the files in a subdirectory, and only add that subdirectory to .gitignore?
This will make the repo directory a bit cleaner.

**Comment by marco-c** [comment]
I've filed #28 for this.

**Comment by rhcu** [comment]
Yep, I'll try. :)

**Comment by rhcu** [comment]
Can I download them to `tools` and only add `firefox` then?

**Comment by marco-c** [comment]
Yes, good idea. So we don't even need to update .gitignore.
