### ISSUE TITLE
Download coverage report for diffing

### ISSUE THREAD

**Issue by marco-c** [marco-c/coverage-crawler#42]
When we download the Firefox build, we should also download the full coverage report (so we can diff it with the coverage reports generated by the crawler).

**Comment by marco-c** [comment]
The first step would be to make sure https://github.com/marco-c/firefox-code-coverage still works, if it doesn't work it needs to be fixed.

**Comment by marco-c** [comment]
Then, we need to make it possible to load https://github.com/marco-c/firefox-code-coverage as a module, so we don't have to reimplement it again.

**Comment by rhcu** [comment]
It works: the report file is generated as HTML with the overall coverage rate:
  lines......: 62.8% (1956347 of 3113045 lines)
  functions..: 67.1% (390379 of 581625 functions)

**Comment by marco-c** [comment]
Awesome, I landed some fixes last week, but I wasn't sure it was fully fixed. The percentage looks more or less correct (there might be some minor differences for some things we filter out in the reports on codecov.io).
