### ISSUE TITLE
Write script to download the latest Firefox coverage build

### ISSUE THREAD

**Issue by marco-c** [marco-c/coverage-crawler#5]

**Comment by rhcu** [comment]
Hi! 
I wanted to start working on this issue. I found out this resource: [Measuring Code Coverage on Firefox](https://developer.mozilla.org/en-US/docs/Mozilla/Testing/Measuring_Code_Coverage_on_Firefox). Just to clarify, what do you mean by Firefox coverage build?

**Comment by marco-c** [comment]
The Firefox coverage build is a build of Firefox which is instrumented to collect and emit coverage information.
Here's the latest one: https://queue.taskcluster.net/v1/task/YUrr0ECgQduNQQp5E0-mYw/runs/0/artifacts/public/build/target.tar.bz2

The script to download the latest build should:
1) Use the Taskcluster index API to retrieve the task ID that generated the build (https://index.taskcluster.net/v1/task/gecko.v2.mozilla-central.latest.firefox.linux64-ccov-opt)
2) Download the `target.tar.bz2` artifact from the Taskcluster queue
3) Extract the artifact

You can use this library for interacting with Taskcluster: https://github.com/taskcluster/taskcluster-client.py.
