### ISSUE TITLE
Test the crawler on some website and evaluate the generated data

### ISSUE THREAD

**Issue by marco-c** [marco-c/coverage-crawler#51]
We should try to run the crawler on a website, generate the diff and analyze it to see if there's anything interesting and to see if there are any improvements we need to make.

**Comment by marco-c** [comment]
Can you list here a few examples? Especially of the case where there's None in the baseline report and covered by crawler.
You can upload the JSON file here after zipping it and you can write here the names of a few source files where you're seeing this.

**Comment by rhcu** [comment]
[diff.json.zip](https://github.com/marco-c/coverage-crawler/files/2103620/diff.json.zip)
According to `diff.py`, the value in diff report can be different from 0, 1 or Null only in case if in the baseline report the value is None (https://github.com/rhcu/coverage-crawler/blob/7a7141931921fef0127d792e399687d43af5df69/diff.py#L8) - then the value from report is added to diif.json.  So, in the uploaded report values > 1 can be noticed in, for example, `image/VectorImage.cpp`, `js/src/vm/Runtime.cpp`, `toolkit/components/url-classifier/nsUrlClassifierProxies.h`, etc.

**Comment by marco-c** [comment]
I'll try to look at the diff tomorrow and see what's wrong. A line which is None in baseline and not None in the crawler report is weird, as for a given build we should have the same coverable lines. Are you sure you downloaded the coverage report and the gcno file for the exact same build?

**Comment by rhcu** [comment]
Nope. I've used coverage report from the previous week since wanted to obscure the download. I'll redo this. There are no way to prevent the full download for testing, yes?

**Comment by marco-c** [comment]
I would clean the tools directory and the current baseline, run `latest_cov_build.py` once and then not run it again for a while. This way you always use the same build and the same baseline report.

**Comment by rhcu** [comment]
Tested the crawler with 5 websites that are in `websites.txt` file [Will add small issue relevant to crawling]. Regarding the report, only 1.3% of uncovered parts in `diff.json`. :) 106 functions that were executed by crawler but weren't by unit tests. As far as I've analyzed, there were no issues that I've described previously (i.e. no parts that are None in baseline report but are covered by crawler). There are some files that are fully uncovered: for example, two of the files correspond to [ this one on GitHub](https://github.com/mitls/hacl-c/blob/master/Hacl_Chacha20_Vec128.c ) and another file from this repository- as I understood, it is a cryptographic library. 
I've added the zipped HTML report if you are interested.
[report.zip](https://github.com/marco-c/coverage-crawler/files/2120153/report.zip)

**Comment by marco-c** [comment]
> There are some files that are fully uncovered

Do you mean fully uncovered in the baseline and covered by the crawler?

**Comment by marco-c** [comment]
The report is quite interesting! I think we're making good progress!

**Comment by rhcu** [comment]
Yes.

**Comment by marco-c** [comment]
I've filed https://github.com/marco-c/coverage-crawler/issues/76 to ignore third-party code. While it is still intersting (this is why it should be an option true by default, but still an option), it's less interesting than the rest.

**Comment by sylvestre** [comment]
> only 1.3%

On the Firefox scale, this is still huge :)

**Comment by marco-c** [comment]
Continuing in https://github.com/marco-c/coverage-crawler/issues/92.
