### ISSUE TITLE
Clean coverage info if equal in both baseline_report and report

### ISSUE THREAD

**Issue by rhcu** [marco-c/coverage-crawler#57]
I am trying to find something interesting in diff report and seems that if coverage lists are similar it is better to add the clean list in diff report as it made with functions here (https://github.com/rhcu/coverage-crawler/blob/c265d83b49f2ed3ffbfc5800d0d6179e91550ac0/diff.py#L20) to improve readability.

**Comment by marco-c** [comment]
Can you build a simple example to show why it would be better?

**Comment by rhcu** [comment]
For example, if we have source file with coverage `[null, null, 0, 1, 4, null, 0, null,0]` both in baseline report and in report, and in diff report we will get `[null, null, 0, 0, 0, null, 0, null, 0]`, what doesn't give much information except that there are no problems with coverage. In real files, these lists can be quite large and, probably, setting them as `[]` in diff report can improve readability.

**Comment by marco-c** [comment]
Ah ok, I misunderstood your first comment :)
Makes sense! Actually in such a case, we should be even more aggressive and just completely remove the file from the diff report.
