### ISSUE TITLE
Add option to ignore hit counts

### ISSUE THREAD

**Issue by marco-c** [marco-c/coverage-crawler#63]
Hit counts are not perfect, so making the diff could be a problem.
We could add an option to the diffing function to always consider hit counts > 0 as being 1.

**Comment by marco-c** [comment]
So if in the baseline it's 5 and in the report it's 1, the diff would be 0 if this option is enabled.

**Comment by rhcu** [comment]
I have something similar here: https://github.com/marco-c/coverage-crawler/blob/c6880494cd34c90a599d7dd6eb884d057db456cb/diff.py#L12, if I am not mistaking. If coverage in the report is smaller than in the baseline, I set it to be 0 in the diff report. Or, did I misunderstand the issue?

**Comment by marco-c** [comment]
What I mean is that, when the option to ignore hit counts is set, https://github.com/marco-c/coverage-crawler/blob/c6880494cd34c90a599d7dd6eb884d057db456cb/diff.py#L10 should return 0 too.

**Comment by marco-c** [comment]
That is, if both j and i are > 0, then the result should be 0 instead of j - i (only if the option to ignore hit counts is set).

**Comment by rhcu** [comment]
So, if in the baseline it's 1 and in the report it's 5, 0 should be returned?

**Comment by marco-c** [comment]
Yes, exactly (but only if the user uses an option to ignore hit counts).
