### ISSUE TITLE
Make latest_cov_build.py accept a "revision" parameter to choose which build to download

### ISSUE THREAD

**Issue by marco-c** [marco-c/coverage-crawler#75]
This way, we don't need to re-download the artifacts all the time, but we can keep using the same ones for a longer time.

**Comment by marco-c** [comment]
We can get the task ID from the revision.
Instead of https://github.com/marco-c/coverage-crawler/blob/2dac2e362f57f03f1c9c331462108a33e032a44a/latest_cov_build.py#L36, when the 'revision' option is passed, you can retrieve the taskId from a URL like `https://index.taskcluster.net/v1/task/gecko.v2.mozilla-central.revision.47e81ea1ef10189ef210867934bf36e14cf223dc.firefox.linux64-debug` (where `47e81ea1ef10189ef210867934bf36e14cf223dc` is the revision).

**Comment by rhcu** [comment]
Ok, thanks. :)
