### ISSUE TITLE
Add an option to ignore third-party files

### ISSUE THREAD

**Issue by marco-c** [marco-c/coverage-crawler#76]
We use several libraries in Firefox from third-party, while it's interesting to know what parts of these libraries are not tested but then used while navigating the web, it's more interesting to know what parts of the code we actually write are untested but used.

We should add an option to ignore third-party files.

We have a list of directories containing third-party code at https://hg.mozilla.org/mozilla-central/raw-file/tip/tools/rewriting/ThirdPartyPaths.txt. We just need to download this file (at the right revision), then if the option is enabled we ignore all files that are in those directories.

**Comment by rhcu** [comment]
Found out that I'm already downloading it when cloning Mozilla-central. :)

**Comment by marco-c** [comment]
Right, it's in the repository itself :smile:
