### ISSUE TITLE
Set up Travis

### ISSUE THREAD

**Issue by marco-c** [marco-c/coverage-crawler#9]
Initially, it should just run flake8 for linting.

**Comment by Sush0512** [comment]
Hi @marco-c 
I started working on this issue. I have few doubts regarding the following
- Why are we using `test-requirements.txt` and `requirements-test.txt` two files to list the packages needed? Should I add the packages to one file?
- In `.travis.yml` file we are using test-requirements.txt file to download the dependencies, I guess the file needs to be updated to add flask-isort package.

I have updated the file and checked the build status on the forked repo, the build is passing, just want to have a deeper insight on the list of files.

Thank you

**Comment by marco-c** [comment]
Oh, sorry, I hadn't noticed I had already created a .travis.yml file in the repository. So there's nothing to do here.

> Why are we using test-requirements.txt and requirements-test.txt two files to list the packages needed? Should I add the packages to one file?

The `requirements.txt` is for packages needed to run the project, the `requirements-test.txt` is for packages needed to work on the project.
