### ISSUE TITLE
Don't use same elements twice

### ISSUE THREAD

**Issue by rhcu** [marco-c/coverage-crawler#91]
I'm running the crawler and sometimes it repeats elements. Probably, I can add a set for `already_used_elems` in the same way as for not clickable ones?

**Comment by marco-c** [comment]
Maybe we should prefer elements we haven't used yet, but we shouldn't completely ignore the ones we have already used?

**Comment by rhcu** [comment]
But won't they actually give much information if interacted more than once? I used one site and there were only 6 elements (all with a property to open a new window) and crawler was just looping around those. :)

**Comment by marco-c** [comment]
They might give more information in some cases, e.g. this stupid example found online: https://jsfiddle.net/z66WF/.
I agree in most cases they won't give much info, so we should give them less priority.
One way to implement this would be to have a set of already clicked elements, when we have to choose an element we look first at the remaining elements (set(all_elements) - already_clicked_set) and then at the already clicked ones.
