### ISSUE TITLE
Fix the generation of JS part of the reports

### ISSUE THREAD

**Issue by marco-c** [marco-c/coverage-crawler#98]
See https://github.com/marco-c/coverage-crawler/issues/92#issuecomment-402325103 and following comments.

**Comment by rhcu** [comment]
It is fixed when I replace `.info` file with a zipped archive containing this file, while a single `.info` file is skipped by grcov giving an error 'No input file found'. Does `grcov` work only with archived lcov files?

**Comment by marco-c** [comment]
We should probably store the info file in a separate directory, and point grcov to the directory instead of the file directly.
I'll file an issue for grcov to handle paths to files too.
